# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'newsletter mailing lists',
                'default_related_name': 'mailing_lists',
                'verbose_name': 'newsletter mailing list',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('template', models.CharField(choices=[('Classic: Post list with 1 banner', 'Classic: Post list with 1 banner')], max_length=255)),
                ('email_html', models.TextField()),
                ('web_html', models.TextField()),
                ('email_views', models.PositiveIntegerField(blank=True, default=0)),
                ('web_views', models.PositiveIntegerField(blank=True, default=0)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('mailing_lists', models.ManyToManyField(blank=True, related_name='newsletters', to='stentor.MailingList')),
            ],
            options={
                'verbose_name_plural': 'newsletters',
                'default_related_name': 'newsletters',
                'verbose_name': 'newsletter',
            },
        ),
        migrations.CreateModel(
            name='ScheduledSending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_date', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sendings', to='stentor.Newsletter')),
            ],
            options={
                'verbose_name_plural': 'scheduled sendings of newslettters',
                'default_related_name': 'scheduled_sendings',
                'verbose_name': 'scheduled sending of newsletter',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(blank=True)),
                ('mailing_lists', models.ManyToManyField(related_name='subscribers', to='stentor.MailingList')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'newsletter subscribers',
                'default_related_name': 'subscribers',
                'verbose_name': 'newsletter subscriber',
            },
        ),
        migrations.AddField(
            model_name='scheduledsending',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sendings', to='stentor.Subscriber'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='newsletters', to='stentor.Subscriber'),
        ),
    ]
