# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='template',
            field=models.CharField(choices=[('default', 'default')], max_length=255),
        ),
    ]
