# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stentor', '0002_auto_20170104_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
