# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 13:34
#
# NOTE: This is **destructive** in nature. The data contained in email_views
# and web_views will be lost after running it.
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models

from stentor.settings import settings as stentor_conf


class Migration(migrations.Migration):

    dependencies = [
        ('stentor', '0003_auto_20170116_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='email_views',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='web_views',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='custom_email_html',
            field=models.TextField(blank=True, help_text="Custom HTML for the newsletter's email views. The template selected should support this, for this to have any effect."),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='custom_web_html',
            field=models.TextField(blank=True, help_text="Custom HTML for the newsletter's web views. The template selected should support this, for this to have any effect."),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email_impressions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='past_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='web_impressions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email_html',
            field=models.TextField(help_text='This is filled automatically.'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='mailing_lists',
            field=models.ManyToManyField(blank=True, help_text='Select the mailing lists, to the subscribers of which, the newsletter should be sent to. If a subscriber is in more than one mailing list, the newsletter will be sent only once to them.', related_name='newsletters', to='stentor.MailingList'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribers',
            field=models.ManyToManyField(blank=True, help_text='Additional subscribers where the newsletter should be sent to. If the selected subscribers are in any selected mailing lists, the newletter will still be sent only once to them.', related_name='explicitly_assigned_newsletters', to='stentor.Subscriber'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='template',
            field=models.CharField(choices=stentor_conf.TEMPLATES, max_length=255),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='web_html',
            field=models.TextField(help_text='This is filled automatically.'),
        ),
    ]
