# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-21 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stentor', '0004_auto_20171221_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='email_html',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='web_html',
        ),
    ]
