# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stentor', '0005_auto_20171221_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='template',
            field=models.CharField(max_length=255),
        ),
    ]
